### ISSUE TITLE
Getting error when running main.py

### ISSUE THREAD

**Issue by ketanmalempati** [madingess/EasyApplyBot#33]
Traceback (most recent call last):
  File "/content/EasyApplyBot/source/app/main.py", line 7, in <module>
    from linkedineasyapply import LinkedinEasyApply
  File "/content/EasyApplyBot/source/app/linkedineasyapply.py", line 1, in <module>
    import time, random, csv, pyautogui, pdb, traceback, sys
  File "/usr/local/lib/python3.10/dist-packages/pyautogui/__init__.py", line 241, in <module>
    import mouseinfo
  File "/usr/local/lib/python3.10/dist-packages/mouseinfo/__init__.py", line 223, in <module>
    _display = Display(os.environ['DISPLAY'])
  File "/usr/lib/python3.10/os.py", line 680, in __getitem__
    raise KeyError(key) from None
KeyError: 'DISPLAY'

**Comment by utkarshb95** [comment]
Seems like this problem is in your end. Check packages and python installation are proper.

**Comment by ketanmalempati** [comment]
Could you share the packages used and their versions?

**Comment by utkarshb95** [comment]
@ketanmalempati  I only installed the packages from requirements.txt file provided in this repo.

**Comment by madingess** [comment]
This comes from the initialization of one of the dependencies and is unrelated to this project. It seems like there be some weird configuration with your local environment. Perhaps this [SO post](https://stackoverflow.com/a/55216524) will solve your issue?
